export const mockFollowers = [
  {
    login: "Mr-spShuvo",
    id: 22437186,
    node_id: "MDQ6VXNlcjIyNDM3MTg2",
    avatar_url: "https://avatars1.githubusercontent.com/u/22437186?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Mr-spShuvo",
    html_url: "https://github.com/Mr-spShuvo",
    followers_url: "https://api.github.com/users/Mr-spShuvo/followers",
    following_url:
      "https://api.github.com/users/Mr-spShuvo/following{/other_user}",
    gists_url: "https://api.github.com/users/Mr-spShuvo/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Mr-spShuvo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Mr-spShuvo/subscriptions",
    organizations_url: "https://api.github.com/users/Mr-spShuvo/orgs",
    repos_url: "https://api.github.com/users/Mr-spShuvo/repos",
    events_url: "https://api.github.com/users/Mr-spShuvo/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Mr-spShuvo/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "jlsjefferson",
    id: 53836950,
    node_id: "MDQ6VXNlcjUzODM2OTUw",
    avatar_url: "https://avatars3.githubusercontent.com/u/53836950?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jlsjefferson",
    html_url: "https://github.com/jlsjefferson",
    followers_url: "https://api.github.com/users/jlsjefferson/followers",
    following_url:
      "https://api.github.com/users/jlsjefferson/following{/other_user}",
    gists_url: "https://api.github.com/users/jlsjefferson/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/jlsjefferson/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/jlsjefferson/subscriptions",
    organizations_url: "https://api.github.com/users/jlsjefferson/orgs",
    repos_url: "https://api.github.com/users/jlsjefferson/repos",
    events_url: "https://api.github.com/users/jlsjefferson/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/jlsjefferson/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "rumd3x",
    id: 12579932,
    node_id: "MDQ6VXNlcjEyNTc5OTMy",
    avatar_url: "https://avatars1.githubusercontent.com/u/12579932?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rumd3x",
    html_url: "https://github.com/rumd3x",
    followers_url: "https://api.github.com/users/rumd3x/followers",
    following_url: "https://api.github.com/users/rumd3x/following{/other_user}",
    gists_url: "https://api.github.com/users/rumd3x/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rumd3x/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rumd3x/subscriptions",
    organizations_url: "https://api.github.com/users/rumd3x/orgs",
    repos_url: "https://api.github.com/users/rumd3x/repos",
    events_url: "https://api.github.com/users/rumd3x/events{/privacy}",
    received_events_url: "https://api.github.com/users/rumd3x/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "migtam628",
    id: 26477083,
    node_id: "MDQ6VXNlcjI2NDc3MDgz",
    avatar_url: "https://avatars3.githubusercontent.com/u/26477083?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/migtam628",
    html_url: "https://github.com/migtam628",
    followers_url: "https://api.github.com/users/migtam628/followers",
    following_url:
      "https://api.github.com/users/migtam628/following{/other_user}",
    gists_url: "https://api.github.com/users/migtam628/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/migtam628/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/migtam628/subscriptions",
    organizations_url: "https://api.github.com/users/migtam628/orgs",
    repos_url: "https://api.github.com/users/migtam628/repos",
    events_url: "https://api.github.com/users/migtam628/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/migtam628/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "wheniconquer",
    id: 8820678,
    node_id: "MDQ6VXNlcjg4MjA2Nzg=",
    avatar_url: "https://avatars3.githubusercontent.com/u/8820678?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/wheniconquer",
    html_url: "https://github.com/wheniconquer",
    followers_url: "https://api.github.com/users/wheniconquer/followers",
    following_url:
      "https://api.github.com/users/wheniconquer/following{/other_user}",
    gists_url: "https://api.github.com/users/wheniconquer/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/wheniconquer/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/wheniconquer/subscriptions",
    organizations_url: "https://api.github.com/users/wheniconquer/orgs",
    repos_url: "https://api.github.com/users/wheniconquer/repos",
    events_url: "https://api.github.com/users/wheniconquer/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/wheniconquer/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "dennohpeter",
    id: 29105876,
    node_id: "MDQ6VXNlcjI5MTA1ODc2",
    avatar_url: "https://avatars3.githubusercontent.com/u/29105876?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/dennohpeter",
    html_url: "https://github.com/dennohpeter",
    followers_url: "https://api.github.com/users/dennohpeter/followers",
    following_url:
      "https://api.github.com/users/dennohpeter/following{/other_user}",
    gists_url: "https://api.github.com/users/dennohpeter/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/dennohpeter/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/dennohpeter/subscriptions",
    organizations_url: "https://api.github.com/users/dennohpeter/orgs",
    repos_url: "https://api.github.com/users/dennohpeter/repos",
    events_url: "https://api.github.com/users/dennohpeter/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/dennohpeter/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "abdussamiakanda",
    id: 48517653,
    node_id: "MDQ6VXNlcjQ4NTE3NjUz",
    avatar_url: "https://avatars1.githubusercontent.com/u/48517653?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/abdussamiakanda",
    html_url: "https://github.com/abdussamiakanda",
    followers_url: "https://api.github.com/users/abdussamiakanda/followers",
    following_url:
      "https://api.github.com/users/abdussamiakanda/following{/other_user}",
    gists_url: "https://api.github.com/users/abdussamiakanda/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/abdussamiakanda/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/abdussamiakanda/subscriptions",
    organizations_url: "https://api.github.com/users/abdussamiakanda/orgs",
    repos_url: "https://api.github.com/users/abdussamiakanda/repos",
    events_url: "https://api.github.com/users/abdussamiakanda/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/abdussamiakanda/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ronsiu-712",
    id: 56333543,
    node_id: "MDQ6VXNlcjU2MzMzNTQz",
    avatar_url: "https://avatars3.githubusercontent.com/u/56333543?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ronsiu-712",
    html_url: "https://github.com/ronsiu-712",
    followers_url: "https://api.github.com/users/ronsiu-712/followers",
    following_url:
      "https://api.github.com/users/ronsiu-712/following{/other_user}",
    gists_url: "https://api.github.com/users/ronsiu-712/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ronsiu-712/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/ronsiu-712/subscriptions",
    organizations_url: "https://api.github.com/users/ronsiu-712/orgs",
    repos_url: "https://api.github.com/users/ronsiu-712/repos",
    events_url: "https://api.github.com/users/ronsiu-712/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ronsiu-712/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "irshadbaruah",
    id: 67238365,
    node_id: "MDQ6VXNlcjY3MjM4MzY1",
    avatar_url: "https://avatars2.githubusercontent.com/u/67238365?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/irshadbaruah",
    html_url: "https://github.com/irshadbaruah",
    followers_url: "https://api.github.com/users/irshadbaruah/followers",
    following_url:
      "https://api.github.com/users/irshadbaruah/following{/other_user}",
    gists_url: "https://api.github.com/users/irshadbaruah/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/irshadbaruah/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/irshadbaruah/subscriptions",
    organizations_url: "https://api.github.com/users/irshadbaruah/orgs",
    repos_url: "https://api.github.com/users/irshadbaruah/repos",
    events_url: "https://api.github.com/users/irshadbaruah/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/irshadbaruah/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Aniruzzaman-anir",
    id: 55508410,
    node_id: "MDQ6VXNlcjU1NTA4NDEw",
    avatar_url: "https://avatars1.githubusercontent.com/u/55508410?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Aniruzzaman-anir",
    html_url: "https://github.com/Aniruzzaman-anir",
    followers_url: "https://api.github.com/users/Aniruzzaman-anir/followers",
    following_url:
      "https://api.github.com/users/Aniruzzaman-anir/following{/other_user}",
    gists_url: "https://api.github.com/users/Aniruzzaman-anir/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Aniruzzaman-anir/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Aniruzzaman-anir/subscriptions",
    organizations_url: "https://api.github.com/users/Aniruzzaman-anir/orgs",
    repos_url: "https://api.github.com/users/Aniruzzaman-anir/repos",
    events_url:
      "https://api.github.com/users/Aniruzzaman-anir/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Aniruzzaman-anir/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "HackerWithDrip",
    id: 68540614,
    node_id: "MDQ6VXNlcjY4NTQwNjE0",
    avatar_url: "https://avatars2.githubusercontent.com/u/68540614?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/HackerWithDrip",
    html_url: "https://github.com/HackerWithDrip",
    followers_url: "https://api.github.com/users/HackerWithDrip/followers",
    following_url:
      "https://api.github.com/users/HackerWithDrip/following{/other_user}",
    gists_url: "https://api.github.com/users/HackerWithDrip/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/HackerWithDrip/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/HackerWithDrip/subscriptions",
    organizations_url: "https://api.github.com/users/HackerWithDrip/orgs",
    repos_url: "https://api.github.com/users/HackerWithDrip/repos",
    events_url: "https://api.github.com/users/HackerWithDrip/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/HackerWithDrip/received_events",
    type: "User",
    site_admin: false,
  },
];
