export const mockUser = {
  login: "AhmadJaber",
  id: 31383347,
  node_id: "MDQ6VXNlcjMxMzgzMzQ3",
  avatar_url: "https://avatars3.githubusercontent.com/u/31383347?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/AhmadJaber",
  html_url: "https://github.com/AhmadJaber",
  followers_url: "https://api.github.com/users/AhmadJaber/followers",
  following_url:
    "https://api.github.com/users/AhmadJaber/following{/other_user}",
  gists_url: "https://api.github.com/users/AhmadJaber/gists{/gist_id}",
  starred_url: "https://api.github.com/users/AhmadJaber/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AhmadJaber/subscriptions",
  organizations_url: "https://api.github.com/users/AhmadJaber/orgs",
  repos_url: "https://api.github.com/users/AhmadJaber/repos",
  events_url: "https://api.github.com/users/AhmadJaber/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/AhmadJaber/received_events",
  type: "User",
  site_admin: false,
  name: "Ashik Ahmad Jaber",
  company: "1mandev",
  blog: "https://www.linkedin.com/in/ashik-ahmad-jaber-993207143/",
  location: "Khulna, Bangladesh",
  email: null,
  hireable: true,
  bio: "Software Developer, Love JavaScript. Enjoy coding React & NodeJS",
  twitter_username: null,
  public_repos: 26,
  public_gists: 1,
  followers: 11,
  following: 150,
  created_at: "2017-08-27T09:19:09Z",
  updated_at: "2020-11-08T20:09:48Z",
};
